DrinkCatalog/Areas/Admin/Controllers/BrandController.cs
using DrinkCatalog.Data.Models;
using DrinkCatalog.Data.Repository.IRepository;
using DrinkCatalog.Services.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DrinkCatalog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public IActionResult Index()
        {
            var brands = _brandService.GetAllBrands();
            return View(brands);
        }

        public IActionResult CreateBrand()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateBrand(Brand brand)
        {
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = _brandService.CreateBrand(brand);
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        public IActionResult EditBrand(int id)
        {
            var brand = _brandService.GetBrandById(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        public IActionResult EditBrand(Brand brand)
        {
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = _brandService.EditBrand(brand);
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        public IActionResult DeleteBrand(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var brandForDelete = _brandService.GetBrandById(id);
            if (brandForDelete == null)
            {
                return NotFound();
            }
            return View(brandForDelete);
        }

        [HttpPost]
        [ActionName("DeleteBrand")]
        public IActionResult DeleteBrandPost(int id)
        {
            TempData["SuccessMessage"] = _brandService.DeleteBrand(id);
            return RedirectToAction("Index");
        }
    }
}

DrinkCatalog/Areas/Admin/Controllers/CoinController.cs
using DrinkCatalog.Data.Models;
using DrinkCatalog.Data.Repository.IRepository;
using DrinkCatalog.Services.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DrinkCatalog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CoinController : Controller
    {
        private readonly ICoinService _coinService;

        public CoinController(ICoinService coinService)
        {
            _coinService = coinService;
        }

        public IActionResult Index()
        {
            var coins = _coinService.GetAllCoins();
            return View(coins);
        }

        public IActionResult AddCoin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCoin(Coin coin)
        {
            var result = _coinService.AddOrUpdateCoin(coin);

            if (result.Contains("Номинал монеты"))
            {
                ModelState.AddModelError("", result);
                TempData["ErrorMessage"] = result;
                return View(coin);
            }

            TempData["SuccessMessage"] = result;
            return RedirectToAction(nameof(Index));
        }

        public IActionResult EditCoin(int id)
        {
            var coin = _coinService.GetCoinById(id);
            if (coin == null)
            {
                return NotFound();
            }
            return View(coin);
        }

        [HttpPost]
        public IActionResult EditCoin(Coin coin)
        {
            if (ModelState.IsValid)
            {
                var result = _coinService.EditCoin(coin);
                TempData["SuccessMessage"] = result;
                return RedirectToAction(nameof(Index));
            }
            return View(coin);
        }
    }
}

DrinkCatalog/Areas/Admin/Controllers/DrinkController.cs
using DrinkCatalog.Data.Models;
using DrinkCatalog.Data.Models.ViewModels;
using DrinkCatalog.Services.IService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SixLabors.ImageSharp;

namespace DrinkCatalog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DrinkController : Controller
    {
        private readonly IDrinkImportService _drinkImportService;
        private readonly IDrinkService _drinkService;
        private readonly IImageService _imageService;
        private readonly IBrandService _brandService;

        public DrinkController(IDrinkService drinkService, IImageService imageService, IDrinkImportService drinkImportService, IBrandService brandService)
        {
            _drinkService = drinkService;
            _imageService = imageService;
            _drinkImportService = drinkImportService;
            _brandService = brandService;
        }


        public IActionResult Index()
        {
            var drinks = _drinkService.GetAllDrinks();
            return View(drinks);
        }

        public IActionResult CreateDrink()
        {
            IEnumerable<SelectListItem> brandList = _brandService.GetAllBrands()
                    .Select(u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.BrandId.ToString()
                    });

            DrinkVM drinkVM = new()
            {
                Drink = new Drink(),
                BrandList = brandList
            };
            return View(drinkVM);
        }

        [HttpPost]
        public IActionResult CreateDrink(DrinkVM drinkVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    drinkVM.Drink.ImageUrl = _imageService.SaveImage(file, @"Img\Drink");
                }
                else
                {
                    TempData["ErrorMessage"] = "Добавьте изображение";
                    return View(drinkVM);
                }
                _drinkService.AddDrink(drinkVM.Drink);
                TempData["SuccessMessage"] = "Напиток успешно создан";
                return RedirectToAction("Index");
            }
            return View(drinkVM);
        }

        public IActionResult EditDrink(int id)
        {
            IEnumerable<SelectListItem> brandList = _brandService.GetAllBrands()
                   .Select(u => new SelectListItem
                   {
                       Text = u.Name,
                       Value = u.BrandId.ToString()
                   });

            var drinkVM = new DrinkVM
            {
                Drink = _drinkService.GetDrinkById(id),
                BrandList = brandList
            };
            return View(drinkVM);
        }


        [HttpPost]
        public IActionResult EditDrink(DrinkVM drinkVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    _imageService.DeleteImage(drinkVM.Drink.ImageUrl);
                    drinkVM.Drink.ImageUrl = _imageService.SaveImage(file, @"Img\Drink");
                }
                _drinkService.UpdateDrink(drinkVM.Drink);
                TempData["SuccessMessage"] = "Напиток успешно изменен";
                return RedirectToAction("Index");
            }
            return View(drinkVM);
        }


        public IActionResult DeleteDrink(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var drinkForDelete = _drinkService.GetDrinkById(id);
            if (drinkForDelete == null)
            {
                return NotFound();
            }
            return View(drinkForDelete);
        }

        [HttpPost]
        [ActionName("DeleteDrink")]
        public IActionResult DeleteDrinkPost(int id)
        {
            _drinkService.DeleteDrink(id);
            TempData["SuccessMessage"] = "Напиток успешно удален";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ImportDrinks(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                TempData["ErrorMessage"] = "Выберите файл для загрузки.";
                return RedirectToAction("Index");
            }

            using (var stream = new MemoryStream())
            {
                await file.CopyToAsync(stream);
                var (drinks, errors) = await _drinkImportService.ImportDrinksAsync(stream);

                if (errors.Any())
                {
                    TempData["ErrorMessage"] = string.Join("<br/>", errors);
                    return RedirectToAction("Index");
                }

                foreach (var drink in drinks)
                {
                    _drinkService.AddDrink(drink);
                }

                TempData["SuccessMessage"] = "Товары успешно импортированы.";
                return RedirectToAction("Index");
            }
        }
    }
}

DrinkCatalog/Areas/Customer/Controllers/ShoppingCartController.cs
using DrinkCatalog.Data.Models.ViewModels;
using DrinkCatalog.Data.Repository.IRepository;
using DrinkCatalog.Services.IService;
using DrinkCatalog.Utility;
using Microsoft.AspNetCore.Mvc;

namespace DrinkCatalog.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(IShoppingCartService shoppingCartService)
        {
            _shoppingCartService = shoppingCartService;
        }

        // Отображение корзины
        public IActionResult Index()
        {
            var cartItems = _shoppingCartService.GetAllCartItems().ToList();

            if (!cartItems.Any())
            {
                TempData["Message"] = "У вас нет ни одного товара, вернитесь на страницу каталога.";
                HttpContext.Session.SetInt32(StaticDetails.SessionCart, 0);
            }

            var cartTotal = cartItems.Sum(x => x.Drink.Price * x.Count);
            var cartItemCount = cartItems.Sum(u => u.Count);

            HttpContext.Session.SetInt32(StaticDetails.SessionCart, cartItemCount);

            var shoppingCartVM = new ShoppingCartVM
            {
                ShoppingCartsList = cartItems.OrderBy(u => u.Id),
                CartTotal = cartTotal,
                CartItemCount = cartItemCount,
                Message = TempData["Message"]?.ToString()
            };
            return View(shoppingCartVM);
        }


        // Удаление товара из корзины
        [HttpPost]
        public IActionResult RemoveFromCart(int cartId)
        {
            _shoppingCartService.RemoveFromCart(cartId);
            return RedirectToAction(nameof(Index));
        }

        // Обновление количества товара
        [HttpPost]
        public IActionResult UpdateCart(int cartId, int newCount)
        {
            var (success, errorMessage) = _shoppingCartService.UpdateCartItemCount(cartId, newCount);
            return Json(new { success, errorMessage });
        }

        // Получение кол-ва товара
        [HttpGet]
        public IActionResult GetCartItemCount()
        {
            var cartItemCount = _shoppingCartService.GetCartItemCount();
            return Json(new { cartItemCount });
        }
    }
}

DrinkCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrinkCatalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrinkCatalog.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"></link>
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css"></link>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DrinkCatalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="Admin" asp-controller="Drink" asp-action="Index">Drinks</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="Admin" asp-controller="Coin" asp-action="Index">Coin</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="ShoppingCart" asp-action="Index">ShoppingCart</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DrinkCatalog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DrinkCatalog/Views/Shared/_Notification.cshtml
@if (TempData["SuccessMessage"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["SuccessMessage"]');
    </script>
}
@if (TempData["ErrorMessage"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["ErrorMessage"]');
    </script>
}